from terriajsscripts.main import *

LF = "\n"


def format_help_into_markdown(p: ArgumentParser):
    help = p.format_help().splitlines()
    return f"""### `{help[0].replace('usage: ', '')}`

```
{LF.join(line for line in help[2:])}
```"""


usage = "\n\n".join(
    [
        format_help_into_markdown(p_share_decode),
        format_help_into_markdown(p_share_encode),
    ]
)
readme = f"""<!-- This document is auto-generated with generatereadme.py. Please do not edit this file directory and instad edit the script file. -->

# terriajs-scripts

## Installing

```
python3 -m pip install .
```

## Usage

{usage}

## Development

Running the command without building & installing:

```
python3 -m terriajsscripts.main
```

"""


with open("README.md", encoding="utf8", mode="w") as fp:
    fp.write(readme)
